LIB=	mu

SRCS+=	console_io.c
SRCS+=	file_io.c
SRCS+=	ipc_dispatch.c
SRCS+=	ipc_request.c
SRCS+=	ns_util.c
SRCS+=	syscalls.S
SRCS+=	util.c

.PATH: ${GLATT_SRC}/mk/core
SRCS+=	core_printf.c

.include "${GLATT_SRC}/mu/build/lib.mk"
