VENDOR=		gnu
PACKAGE=	make
VERSION=	3.81
DISTFILE=	${PACKAGE}-${VERSION}.tar.bz2
DISTDIR=	${PACKAGE}-${VERSION}

CONFIGURE+=	--prefix=${PREFIX}
CONFIGURE+=	--program-prefix=gnu

.include "${GLATT_SRC}/aux/build/vendor.mk"
