KERNEL_CC=	${TOOLCHAIN_TARGET}-gcc
KERNEL_AS=	${TOOLCHAIN_TARGET}-as
KERNEL_LD=	${TOOLCHAIN_TARGET}-ld
KERNEL_NM=	${TOOLCHAIN_TARGET}-nm
KERNEL_SIM=	gxemul

#KERNEL_ABI=	-mabi=64
KERNEL_ENTRY=	start
KERNEL_CPU=	-mcpu=G4
#KERNEL_FORMAT=	elf64-bigmips

KERNEL_SIMFLAGS+=-S
KERNEL_SIMFLAGS+=-E ${KERNEL_MACHINE}
.if defined(KERNEL_SUBMACHINE)
KERNEL_SIMFLAGS+=-e ${KERNEL_SUBMACHINE}
.endif
.if defined(KERNEL_SIMCPUS)
KERNEL_SIMFLAGS+=-n ${KERNEL_SIMCPUS}
.if defined(KERNEL_RANDOMBOOTSTRAPCPU)
KERNEL_SIMFLAGS+=-R
.endif
.endif
.if defined(KERNEL_SIMCLOCKHZ)
KERNEL_SIMFLAGS+=-I ${KERNEL_SIMCLOCKHZ}
.endif
.for simdisk in ${KERNEL_SIMDISKS}
KERNEL_SIMFLAGS+=-d ${simdisk}
.endfor
#.if defined(DISPLAY)
#KERNEL_SIMFLAGS+=-X
#.endif
.if defined(KERNEL_SIMVERBOSE)
KERNEL_SIMFLAGS+=-v
.else
KERNEL_SIMFLAGS+=-q
.endif

simulate-${KERNEL}: ${KERNEL}
	${KERNEL_SIM} ${KERNEL_SIMFLAGS} ${KERNEL}

.if make(simulate-${KERNEL}) || make(simulate)
.INTERRUPT:
	killall ${KERNEL_SIM}
.endif
